apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-v1
spec:
  replicas: 3
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: product-service-v1
  template:
    metadata:
      labels:
        app: product-service-v1
    spec:
      containers:
      - image: jpaezr/product-service-v1
        name: product-service-v1
        ports:
        - containerPort: 3000
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: product-service-v1-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: product-service-v1-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-service-v1-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: product-service-v1-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: product-service-v1-secret
              key: DB_PORT
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: product-service-v1-secret
              key: PORT
