name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Asegura que todo el historial y archivos sean clonados correctamente

      - name: List files in the working directory  # Este paso lista los archivos en el directorio de trabajo
        run: ls -al

      - name: Print current working directory  # Imprime el directorio actual para confirmar el contexto
        run: pwd

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./  # Asegura que el contexto de construcción sea correcto
          file: ./Dockerfile  # Asegúrate de que la ruta del Dockerfile esté bien
          push: true
          tags: aursalva1/product-service-v1:20240915  # Asegúrate de que el tag es correcto

      - name: Log out from Docker Hub
        run: docker logout
