name: Build and Push Docker Image1

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Usa la acción correcta para configurar Buildx

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Usa la versión correcta de build-push-action
        with:
          context: .
          file: Dockerfile
          push: true
          tags: aursalva1/product-service-v1:20240915  # Asegúrate de que el tag es correcto

      - name: Log out from Docker Hub
        run: docker logout
