name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Clona todo el repositorio

      - name: List files in the working directory  # Depurar la estructura de archivos
        run: ls -al

      - name: Print current working directory  # Imprime el directorio actual para confirmar el contexto
        run: pwd

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./  # Contexto de construcción (raíz del repositorio)
          file: ./Dockerfile  # Archivo Dockerfile en la raíz del repositorio
          push: true
          tags: aursalva1/product-service-v1:20240918  # Etiqueta de la imagen
          no-cache: true  # Desactiva el uso de caché en la construcción

      - name: Log out from Docker Hub
        run: docker logout
