name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building product-service-v1 ..."

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: aursalva1/product-service-v:20240915

  promote-to-dev-environment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          echo "promoting into dev environment"
          git config --global user.email ci-bot@argcd.com
          git config --global user.name "ci bot"
          echo "Cloning config repo $CONFIG_REPO_NAME"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO_NAME.git
          cd $CONFIG_REPO_NAME
          echo "Checkout main branch"
          git checkout main
          echo "Updating image tag in values file"
          git add . && git commit -m "update image tag"
          git push
